import {
  HIRING_CATEGORIES,
  normalizeProfileSlug,
  onboardingProgress,
  roleOnboardingDestination,
  safeAssetPath,
  stepsForRole,
  timezoneOverlapSummary,
  validateClientStep,
  validateFreelancerStep,
  validateProfileUpload,
} from './onboarding.js';
import { featureBrandButton, featureBrandLink } from '../../shared/site-chrome.js?v=surface-logo-20260730';
import { openTalentContactDialog } from '../messaging/contact.js?v=client-contact-20260730';
import { safePublicDisplayName, safePublicProfessionalTitle } from '../../shared/public-privacy.js?v=20260811';

const countries=[['AU','Australia'],['CA','Canada'],['DE','Germany'],['FR','France'],['GB','United Kingdom'],['IN','India'],['JP','Japan'],['NZ','New Zealand'],['PH','Philippines'],['PK','Pakistan'],['SG','Singapore'],['US','United States'],['ZA','South Africa']];
const timezones=['UTC','Australia/Perth','Australia/Adelaide','Australia/Brisbane','Australia/Melbourne','Australia/Sydney','America/Chicago','America/Los_Angeles','America/New_York','America/Toronto','Asia/Dubai','Asia/Karachi','Asia/Kolkata','Asia/Manila','Asia/Singapore','Asia/Tokyo','Europe/Berlin','Europe/London','Europe/Paris','Pacific/Auckland'];
const currencies=['AUD','CAD','EUR','GBP','INR','NZD','PKR','SGD','USD','ZAR'];
const companySizes=['solo','2-10','11-50','51-200','201-500','501-1000','1001+'];
const clientLanguages=[['en','English'],['fr','French'],['de','German'],['hi','Hindi'],['ja','Japanese'],['pa','Punjabi'],['ur','Urdu']];
const projectSizes=[['under-1k','Under 1,000'],['1k-5k','1,000–5,000'],['5k-25k','5,000–25,000'],['25k-plus','25,000+'],['ongoing','Ongoing work']];
const engagementTypes=[['hourly','Hourly'],['fixed','Fixed price'],['managed','Managed service'],['flexible','Flexible']];
let root=null;

const esc=value=>{const node=document.createElement('span');node.textContent=value??'';return node.innerHTML};
const options=(values,current,placeholder='Choose one')=>`${placeholder?`<option value="">${esc(placeholder)}</option>`:''}${values.map(item=>{const [value,label]=Array.isArray(item)?item:[item,item];return `<option value="${esc(value)}" ${current===value?'selected':''}>${esc(label)}</option>`}).join('')}`;
const field=(label,name,value,type='text',extra='')=>`<label class="pe-field">${esc(label)}<input data-field="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(label,name,value,values,placeholder)=>`<label class="pe-field">${esc(label)}<select data-field="${name}">${options(values,value,placeholder)}</select></label>`;
const textarea=(label,name,value,rows=5)=>`<label class="pe-field">${esc(label)}<textarea data-field="${name}" rows="${rows}">${esc(value)}</textarea></label>`;
const money=value=>value==null?'':String(Number(value)/100);
const minor=value=>Number.isFinite(Number(value))?Math.round(Number(value)*100):null;
const fail=error=>error?.code==='23505'?'That public profile URL is already taken. Choose another one.':error?.message&&/session/i.test(error.message)?error.message:'We couldn’t save that step. Check your details and try again.';
const blankWorkEntry=()=>({id:null,companyName:'',jobTitle:'',startDate:'',endDate:'',currentlyWorking:false,description:''});
const blankEducationEntry=()=>({id:null,institution:'',qualification:'',fieldOfStudy:'',startYear:'',endYear:''});
const blankLanguageEntry=()=>({originalCode:null,code:'',name:'',proficiency:'professional'});
const collectionField=(label,collection,index,key,value,type='text',extra='')=>`<label class="pe-field">${esc(label)}<input data-collection="${collection}" data-index="${index}" data-key="${key}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const collectionTextarea=(label,collection,index,key,value,rows=3)=>`<label class="pe-field">${esc(label)}<textarea data-collection="${collection}" data-index="${index}" data-key="${key}" rows="${rows}">${esc(value)}</textarea></label>`;
const hasWorkValue=entry=>Boolean(entry.companyName||entry.jobTitle||entry.startDate||entry.endDate||entry.description||entry.currentlyWorking);
const hasEducationValue=entry=>Boolean(entry.institution||entry.qualification||entry.fieldOfStudy||entry.startYear||entry.endYear);
const hasLanguageValue=entry=>Boolean(entry.code||entry.name);

export function validateWorkHistoryEntry(entry){
  if(!hasWorkValue(entry))return null;
  if(!String(entry.companyName||'').trim())return 'Enter the company for each work-history entry.';
  if(!String(entry.jobTitle||'').trim())return 'Enter the job title for each work-history entry.';
  if(!entry.startDate)return 'Choose a start date for each work-history entry.';
  if(!entry.currentlyWorking&&!entry.endDate)return 'Choose an end date or mark the role as current.';
  if(entry.endDate&&entry.endDate<entry.startDate)return 'A work-history end date cannot be before its start date.';
  return null;
}

export function validateEducationEntry(entry){
  if(!hasEducationValue(entry))return null;
  if(!String(entry.institution||'').trim())return 'Enter the institution for each education entry.';
  if(!String(entry.qualification||'').trim())return 'Enter the qualification for each education entry.';
  const startYear=entry.startYear===''?null:Number(entry.startYear),endYear=entry.endYear===''?null:Number(entry.endYear);
  if(startYear!==null&&(!Number.isInteger(startYear)||startYear<1900||startYear>2200))return 'Enter a valid education start year.';
  if(endYear!==null&&(!Number.isInteger(endYear)||endYear<1900||endYear>2200))return 'Enter a valid education end year.';
  if(startYear!==null&&endYear!==null&&endYear<startYear)return 'An education end year cannot be before its start year.';
  return null;
}

export function validateLanguageEntry(entry){
  if(!hasLanguageValue(entry))return null;
  const code=String(entry.code||'').trim().toLowerCase();
  if(!/^[a-z]{2,3}$/.test(code))return 'Use a two- or three-letter language code.';
  if(!String(entry.name||'').trim())return 'Enter the language name.';
  if(!['basic','conversational','professional','native'].includes(entry.proficiency))return 'Choose a valid language proficiency.';
  return null;
}

function showRoot(html){
  if(!root){root=document.createElement('div');root.className='workora-profile-root';document.body.append(root)}
  root.innerHTML=html;
  root.scrollTop=0;
}

export function unmountProfileExperience(){root?.remove();root=null}

async function signedUrl(supabase,bucket,path){if(!path)return null;const {data}=await supabase.storage.from(bucket).createSignedUrl(path,3600);return data?.signedUrl||null}

async function uploadImage({supabase,supabaseUrl,publishableKey,bucket,path,file,onProgress}){
  const {data,error}=await supabase.auth.getSession();
  if(error||!data.session?.access_token)throw new Error('Your session expired. Log in again before uploading.');
  const encoded=path.split('/').map(encodeURIComponent).join('/');
  await new Promise((resolve,reject)=>{
    const request=new XMLHttpRequest();request.open('POST',`${supabaseUrl}/storage/v1/object/${bucket}/${encoded}`);
    request.setRequestHeader('Authorization',`Bearer ${data.session.access_token}`);request.setRequestHeader('apikey',publishableKey);request.setRequestHeader('Content-Type',file.type);request.setRequestHeader('x-upsert','false');
    request.upload.onprogress=event=>event.lengthComputable&&onProgress(Math.round(event.loaded/event.total*100));
    request.onload=()=>request.status>=200&&request.status<300?resolve():reject(new Error('The image could not be uploaded.'));
    request.onerror=()=>reject(new Error('The upload was interrupted.'));
    request.send(file);
  });
}

function profileNavigation(state){
  if(!state.complete){
    return state.role==='client'
      ? [['Find talent','/find-talent'],['How hiring works','/how-it-works/clients'],['Help','/help/client-getting-started']]
      : [['Find work','/find-work'],['How freelancing works','/how-it-works/freelancers'],['Help','/help/freelancer-getting-started']];
  }
  return state.role==='client'
    ? [['Dashboard','/app/client'],['Find talent','/find-talent'],['My jobs','/app/jobs'],['Contracts','/app/contracts'],['Messages','/app/messages'],['Settings','/app/settings']]
    : [['Dashboard','/app/freelancer'],['Find work','/find-work'],['Proposals','/app/proposals'],['Contracts','/app/contracts'],['Messages','/app/messages'],['Settings','/app/settings']];
}
function header(state){const menu=profileNavigation(state).map(([label,path])=>`<a href="${path}" data-route="${path}">${esc(label)}</a>`).join('');return `<header class="pe-header">${featureBrandButton('pe-home')}<nav aria-label="${state.complete?'Account':'Onboarding'} navigation">${menu}</nav><div><span class="pe-role">${esc(state.role)}</span><strong>${esc(state.shared.displayName||'Your account')}</strong><button id="pe-signout">Sign out</button></div></header>`}
function sharedIdentity(state){return `<div class="pe-avatar"><div class="pe-avatar-preview">${state.avatarPreview?`<img src="${esc(state.avatarPreview)}" alt="Profile preview">`:'W'}</div><div><strong>Profile image (optional)</strong><p class="pe-intro">JPG, PNG or WebP · 5 MB maximum</p><label class="pe-file"><input id="pe-avatar-file" type="file" accept="image/jpeg,image/png,image/webp">${state.shared.avatarPath?'Replace image':'Choose image'}</label>${state.shared.avatarPath?'<button class="pe-button" type="button" id="pe-delete-avatar" style="margin-left:8px">Delete image</button>':''}</div></div><div class="pe-grid">${field('Display name','shared.displayName',state.shared.displayName,'text','required')}${select('Country','shared.countryCode',state.shared.countryCode,countries,'Choose a country')}${field('First name','shared.firstName',state.shared.firstName)}${field('Last name','shared.lastName',state.shared.lastName)}${select('Timezone','shared.timezone',state.shared.timezone,timezones,'')}${field('Region or state','shared.region',state.shared.region)}</div>`}
function agreements(state){return `<label class="pe-check"><input data-field="shared.acceptedTerms" type="checkbox" ${state.shared.acceptedTerms?'checked':''}>I agree to the GoWorkora Terms.</label><label class="pe-check"><input data-field="shared.acceptedPrivacy" type="checkbox" ${state.shared.acceptedPrivacy?'checked':''}>I acknowledge the GoWorkora Privacy Policy.</label>`}

function clientStep(state){const {step,client}=state;
  if(step===1)return `<p class="pe-intro">Start with the personal and professional details your future collaborators will use to recognise you.</p>${sharedIdentity(state)}<div class="pe-grid">${field('Job title','client.jobTitle',client.jobTitle,'text','required maxlength="120"')}${field('Department','client.department',client.department,'text','required maxlength="120"')}${field('Hiring responsibility','client.hiringRole',client.hiringRole,'text','required maxlength="120" placeholder="Hiring manager"')}${select('Language preference','client.languageCode',client.languageCode,clientLanguages,'Choose a language')}</div>`;
  if(step===2)return `<p class="pe-intro">Tell professionals who they will work with. Independent clients can continue without a company.</p><label class="pe-check"><input data-field="client.independentClient" type="checkbox" ${client.independentClient?'checked':''}>I’m hiring independently</label>${client.independentClient?'':`<div class="pe-avatar"><div class="pe-avatar-preview">${client.companyLogoPreview?`<img src="${esc(client.companyLogoPreview)}" alt="Company logo preview">`:'GW'}</div><div><strong>Company logo (optional)</strong><p class="pe-intro">JPG, PNG or WebP · 5 MB maximum</p><label class="pe-file"><input id="pe-company-logo-file" type="file" accept="image/jpeg,image/png,image/webp">${client.companyLogoPath?'Replace logo':'Choose logo'}</label></div></div><div class="pe-grid">${field('Company name','client.companyName',client.companyName,'text','required maxlength="160"')}${field('Website','client.companyWebsite',client.companyWebsite,'url','placeholder="https://example.com"')}${select('Company size','client.companySize',client.companySize,companySizes,'Choose a size')}${field('Industry','client.industry',client.industry,'text','required maxlength="120"')}${select('Company country','client.companyCountryCode',client.companyCountryCode,countries,'Choose a country')}</div>${textarea('Company description (20+ characters)','client.companyDescription',client.companyDescription,5)}`}`;
  if(step===3)return `<p class="pe-intro">Choose the areas you hire in and the engagement patterns that best represent your work.</p><div class="pe-grid">${select('Typical project size','client.typicalProjectSize',client.typicalProjectSize,projectSizes,'Choose a project size')}${select('Preferred engagement','client.preferredEngagementType',client.preferredEngagementType,engagementTypes,'Choose an engagement')}</div><div class="pe-options">${HIRING_CATEGORIES.map(category=>`<label class="pe-option ${client.hiringCategories.includes(category)?'selected':''}"><input data-array="hiringCategories" value="${esc(category)}" type="checkbox" ${client.hiringCategories.includes(category)?'checked':''}>${esc(category)}</label>`).join('')}</div>`;
  if(step===4)return `<p class="pe-intro">Set your billing region and preferred display currency.</p><div class="pe-grid">${select('Billing country','client.billingCountry',client.billingCountry,countries,'Choose a country')}${select('Preferred currency','client.preferredCurrency',client.preferredCurrency,currencies,'')}</div>`;
  return `<p class="pe-intro">Review your details and confirm the policies that protect everyone on GoWorkora.</p><div class="pe-collection"><h3>${esc(client.independentClient?'Independent client':client.companyName)}</h3><p>${esc(client.jobTitle)} · ${esc(client.department)} · ${esc(client.hiringRole)}</p><p>${esc(client.hiringCategories.join(', '))}</p><p>${esc(client.typicalProjectSize)} · ${esc(client.preferredEngagementType)} · ${esc(client.preferredCurrency)}</p></div>${agreements(state)}`;
}

function preview(state){const selected=state.skills.filter(skill=>state.freelancer.skillIds.includes(skill.id));return `<article class="pe-public-card" style="margin:0"><div class="pe-public-hero"><div class="pe-public-avatar">${state.avatarPreview?`<img src="${esc(state.avatarPreview)}" alt="Profile preview">`:'W'}</div><div><h1>${esc(state.shared.displayName||'Your name')}</h1><p>${esc(state.freelancer.professionalTitle||'Your professional title')}</p><div class="pe-public-meta"><span>${esc(state.freelancer.primaryCategory||'Professional services')}</span><span>${esc(state.freelancer.yearsExperience||'0')} years experience</span><span>${esc(state.shared.countryCode)}</span><span>${esc(timezoneOverlapSummary(state.shared.timezone))}</span></div></div><strong class="pe-rate">${esc(state.freelancer.currency)} ${esc(state.freelancer.hourlyRate||'—')}/hr</strong></div><div class="pe-public-body"><section><h2>About</h2><p>${esc(state.freelancer.bio||'Your summary')}</p></section><section><h2>Skills</h2><div class="pe-tags">${selected.map(skill=>`<span>${esc(skill.name)}</span>`).join('')}</div></section></div></article>`}

function freelancerStep(state){const {step,shared,freelancer}=state;
  if(step===1)return `<p class="pe-intro">Build a clear professional identity. Private contact details are never shown publicly.</p>${sharedIdentity(state)}${field('Professional title','freelancer.professionalTitle',freelancer.professionalTitle)}${textarea('Professional summary (80+ characters)','freelancer.bio',freelancer.bio,6)}<div class="pe-grid">${field('Public profile URL','freelancer.profileSlug',freelancer.profileSlug)}${select('Location privacy','shared.locationVisibility',shared.locationVisibility,[['country','Show country'],['region','Show region only'],['hidden','Hide location']],'')}</div>`;
  if(step===2){const groups=Object.groupBy?Object.groupBy(state.skills,skill=>skill.category):state.skills.reduce((all,skill)=>{(all[skill.category]??=[]).push(skill);return all},{}),categories=Object.keys(groups).sort((a,b)=>a.localeCompare(b));return `<p class="pe-intro">Choose your main field, record your overall experience, and select at least three skills.</p><div class="pe-grid">${select('Primary professional category','freelancer.primaryCategory',freelancer.primaryCategory,categories,'Choose a category')}${field('Years of professional experience','freelancer.yearsExperience',freelancer.yearsExperience,'number','min="0" max="80" step="0.5" inputmode="decimal"')}</div>${Object.entries(groups).map(([category,skills])=>`<div class="pe-collection"><h3>${esc(category)}</h3><div class="pe-skills">${skills.map(skill=>`<label class="pe-option ${freelancer.skillIds.includes(skill.id)?'selected':''}"><input data-array="skillIds" value="${skill.id}" type="checkbox" ${freelancer.skillIds.includes(skill.id)?'checked':''}>${esc(skill.name)}</label>`).join('')}</div></div>`).join('')}`}
  if(step===3)return `<p class="pe-intro">Set a transparent rate and realistic weekly capacity.</p><div class="pe-grid">${field('Hourly rate','freelancer.hourlyRate',freelancer.hourlyRate,'number','min="1" step="0.01"')}${select('Currency','freelancer.currency',freelancer.currency,currencies,'')}${select('Experience','freelancer.experienceLevel',freelancer.experienceLevel,[['entry','Entry'],['intermediate','Intermediate'],['expert','Expert']],'')}${field('Weekly capacity','freelancer.weeklyCapacity',freelancer.weeklyCapacity,'number','min="1" max="168"')}${select('Availability','freelancer.availabilityStatus',freelancer.availabilityStatus,[['available','Available now'],['limited','Limited'],['unavailable','Unavailable']],'')}${field('Minimum project (optional)','freelancer.minimumProject',freelancer.minimumProject,'number','min="0" step="0.01"')}</div>`;
  if(step===4)return `<p class="pe-intro">Work history, education, and languages are optional. Add as many relevant positions and qualifications as you need. Removed saved entries are deleted only after you choose Save and continue.</p>
    <section class="pe-history-section" aria-labelledby="pe-work-history-heading">
      <div class="pe-collection-heading"><div><span>Professional experience</span><h3 id="pe-work-history-heading">Work history</h3></div><button class="pe-collection-add" type="button" data-add-collection="workHistory">+ Add position</button></div>
      ${state.workHistory.length?state.workHistory.map((entry,index)=>`<article class="pe-history-card">
        <div class="pe-history-card-heading"><div><span>Position ${index+1}</span><strong>${esc(entry.jobTitle||entry.companyName||'New work-history entry')}</strong></div><button type="button" class="pe-collection-remove" data-remove-collection="workHistory" data-index="${index}" aria-label="Remove work history ${index+1}">Remove</button></div>
        <div class="pe-grid">${collectionField('Company','workHistory',index,'companyName',entry.companyName)}${collectionField('Job title','workHistory',index,'jobTitle',entry.jobTitle)}${collectionField('Start date','workHistory',index,'startDate',entry.startDate,'date')}${collectionField('End date','workHistory',index,'endDate',entry.endDate,'date',entry.currentlyWorking?'disabled':'')}</div>
        <label class="pe-check pe-current-role"><input data-collection="workHistory" data-index="${index}" data-key="currentlyWorking" type="checkbox" ${entry.currentlyWorking?'checked':''}>I currently work here</label>
        ${collectionTextarea('Description','workHistory',index,'description',entry.description,3)}
      </article>`).join(''):'<div class="pe-history-empty"><strong>No work history added</strong><p>Add relevant roles to help clients understand your experience.</p></div>'}
    </section>
    <section class="pe-history-section" aria-labelledby="pe-education-heading">
      <div class="pe-collection-heading"><div><span>Qualifications</span><h3 id="pe-education-heading">Education</h3></div><button class="pe-collection-add" type="button" data-add-collection="educationHistory">+ Add education</button></div>
      ${state.educationHistory.length?state.educationHistory.map((entry,index)=>`<article class="pe-history-card">
        <div class="pe-history-card-heading"><div><span>Education ${index+1}</span><strong>${esc(entry.qualification||entry.institution||'New education entry')}</strong></div><button type="button" class="pe-collection-remove" data-remove-collection="educationHistory" data-index="${index}" aria-label="Remove education ${index+1}">Remove</button></div>
        <div class="pe-grid">${collectionField('Institution','educationHistory',index,'institution',entry.institution)}${collectionField('Qualification','educationHistory',index,'qualification',entry.qualification)}${collectionField('Field of study','educationHistory',index,'fieldOfStudy',entry.fieldOfStudy)}${collectionField('Start year','educationHistory',index,'startYear',entry.startYear,'number','min="1900" max="2200" inputmode="numeric"')}${collectionField('End year','educationHistory',index,'endYear',entry.endYear,'number','min="1900" max="2200" inputmode="numeric"')}</div>
      </article>`).join(''):'<div class="pe-history-empty"><strong>No education added</strong><p>Add a qualification when it supports the work you want to do.</p></div>'}
    </section>
    <section class="pe-history-section" aria-labelledby="pe-languages-heading">
      <div class="pe-collection-heading"><div><span>Communication</span><h3 id="pe-languages-heading">Languages</h3></div><button class="pe-collection-add" type="button" data-add-collection="languages">+ Add language</button></div>
      ${state.languages.length?state.languages.map((entry,index)=>`<article class="pe-history-card">
        <div class="pe-history-card-heading"><div><span>Language ${index+1}</span><strong>${esc(entry.name||'New language')}</strong></div><button type="button" class="pe-collection-remove" data-remove-collection="languages" data-index="${index}" aria-label="Remove language ${index+1}">Remove</button></div>
        <div class="pe-grid">${collectionField('Code','languages',index,'code',entry.code,'text','maxlength="3" autocapitalize="none"')}${collectionField('Language','languages',index,'name',entry.name)}<label class="pe-field">Proficiency<select data-collection="languages" data-index="${index}" data-key="proficiency">${options([['basic','Basic'],['conversational','Conversational'],['professional','Professional'],['native','Native']],entry.proficiency,'')}</select></label></div>
      </article>`).join(''):'<div class="pe-history-empty"><strong>No languages added</strong><p>Add the languages clients can use when working with you.</p></div>'}
    </section>`;
  if(step===5)return `<p class="pe-intro">Portfolio is optional. Images are validated and stored in your private user directory.</p><div class="pe-collection"><h3>Featured project</h3><div class="pe-image">${state.portfolio.imagePreview?`<img src="${esc(state.portfolio.imagePreview)}" alt="Portfolio preview">`:'No image selected'}</div><label class="pe-file" style="margin-top:10px"><input id="pe-portfolio-file" type="file" accept="image/jpeg,image/png,image/webp">${state.portfolio.imagePath?'Replace image':'Choose image'}</label>${state.portfolio.id?'<button class="pe-button" type="button" id="pe-delete-portfolio" style="margin-left:8px">Delete item</button>':''}${field('Project title','portfolio.title',state.portfolio.title)}${textarea('Description','portfolio.description',state.portfolio.description,4)}${field('Project URL','portfolio.projectUrl',state.portfolio.projectUrl,'url')}<label class="pe-check"><input data-field="portfolio.isPublished" type="checkbox" ${state.portfolio.isPublished?'checked':''}>Show on my public profile</label></div>`;
  if(step===6)return `<p class="pe-intro">This preview contains public fields only—never email, phone, payment details, moderation data, exact address, or IDs.</p>${preview(state)}`;
  return `<p class="pe-intro">Confirm your profile and policies to publish.</p><div class="pe-collection"><h3>${esc(shared.displayName)}</h3><p>${esc(freelancer.professionalTitle)} · ${esc(freelancer.currency)} ${esc(freelancer.hourlyRate)}/hr</p><p>/find-talent/${esc(freelancer.profileSlug)}</p></div>${agreements(state)}`;
}

function renderWorkspace(state,handlers){
  if(state.complete&&!state.editing){showRoot(`${header(state)}<section class="pe-dashboard"><span class="pe-kicker">Profile complete</span><h1>Welcome back, ${esc(state.shared.displayName)}.</h1><p>Your ${esc(state.role)} profile is ready. Keep it current so every new collaboration starts with the right context.</p><div class="pe-stats"><article><span>Completeness</span><h2>100%</h2><p>All required fields are complete.</p></article><article><span>Account</span><h2>${esc(state.role)}</h2><p>${esc(state.role==='client'?(state.client.independentClient?'Independent client':state.client.companyName):state.freelancer.professionalTitle)}</p></article><article><span>Visibility</span><h2>${esc(state.shared.profileVisibility)}</h2><p>Private contact and payment data remain protected.</p></article></div><a class="pe-button dark" href="${state.role==='client'?'#talent':'#jobs'}">${state.role==='client'?'Find talent':'Find work'}</a> ${state.role==='client'?'<a class="pe-button" href="#talent/saved">Saved talent</a> <a class="pe-button" href="#jobs/manage">Manage jobs</a>':'<a class="pe-button" href="#invitations">Invitations</a>'} <a class="pe-button" href="#contracts">Contracts</a> <button class="pe-button" id="pe-edit">Edit profile</button>${state.role==='freelancer'?` <a class="pe-button" href="#freelancers/${esc(state.freelancer.profileSlug)}">Preview public profile</a>`:''}</section>`);bindCommon(handlers);document.querySelector('#pe-edit').onclick=()=>handlers.edit();return}
  const labels=stepsForRole(state.role),progress=onboardingProgress(state.role,state.step,false);
  showRoot(`${header(state)}<section class="pe-shell"><aside class="pe-side"><span class="pe-kicker">${state.complete?'Edit profile':'Set up your profile'}</span><h1>${state.role==='client'?'Tell us how you hire.':'Show clients your best work.'}</h1><div><small>${progress}% complete · Step ${state.step} of ${labels.length}</small><div class="pe-progress"><i style="width:${progress}%"></i></div></div><ol>${labels.map((label,index)=>`<li class="${index+1===state.step?'active':index+1<state.step?'done':''}"><span>${index+1<state.step?'✓':index+1}</span>${esc(label)}</li>`).join('')}</ol></aside><form class="pe-card" id="pe-form"><span class="pe-kicker">Step ${state.step}</span><h2>${esc(labels[state.step-1])}</h2>${state.role==='client'?clientStep(state):freelancerStep(state)}${state.uploadProgress?`<div class="pe-upload"><i style="width:${state.uploadProgress}%"></i>Uploading image… ${state.uploadProgress}%</div>`:''}${state.notice?`<p class="pe-notice" role="status">✓ ${esc(state.notice)}</p>`:''}${state.error?`<p class="pe-error" role="alert">${esc(state.error)}</p>`:''}<div class="pe-actions"><button class="pe-button" id="pe-back" type="button" ${state.step===1||state.saving?'disabled':''}>Back</button><span>Changes save after every step.</span><button class="pe-button dark" type="submit" ${state.saving?'disabled':''}>${state.saving?'Saving…':state.step===labels.length?(state.complete?'Save profile':'Complete profile'):'Save and continue'}</button></div></form></section>`);
  bindCommon(handlers);bindFields(state,handlers);document.querySelector('#pe-form').onsubmit=handlers.submit;document.querySelector('#pe-back').onclick=()=>handlers.back();
}

function bindCommon(handlers){document.querySelector('#pe-home').onclick=handlers.home;document.querySelector('#pe-signout').onclick=handlers.signOut}
function bindFields(state,handlers){
  document.querySelectorAll('[data-field]').forEach(input=>input.oninput=()=>{const [group,key]=input.dataset.field.split('.');state[group][key]=input.type==='checkbox'?input.checked:input.value;state.error='';if(input.dataset.field==='client.independentClient')renderWorkspace(state,handlers)});
  document.querySelectorAll('[data-array]').forEach(input=>input.onchange=()=>{const target=input.dataset.array==='skillIds'?state.freelancer.skillIds:state.client.hiringCategories;if(input.checked)target.push(input.value);else target.splice(target.indexOf(input.value),1);renderWorkspace(state,handlers)});
  document.querySelectorAll('[data-collection][data-key]').forEach(input=>input.oninput=()=>{const entry=state[input.dataset.collection]?.[Number(input.dataset.index)];if(!entry)return;entry[input.dataset.key]=input.type==='checkbox'?input.checked:input.value;if(input.dataset.key==='currentlyWorking'&&input.checked)entry.endDate='';state.error='';if(input.type==='checkbox')renderWorkspace(state,handlers)});
  document.querySelectorAll('[data-add-collection]').forEach(button=>button.onclick=()=>{const collection=button.dataset.addCollection;if(collection==='workHistory')state.workHistory.push(blankWorkEntry());if(collection==='educationHistory')state.educationHistory.push(blankEducationEntry());if(collection==='languages')state.languages.push(blankLanguageEntry());state.error='';renderWorkspace(state,handlers)});
  document.querySelectorAll('[data-remove-collection]').forEach(button=>button.onclick=()=>{const collection=button.dataset.removeCollection,index=Number(button.dataset.index),entry=state[collection]?.[index];if(!entry)return;if(entry.id){const removed=collection==='workHistory'?state.removedWorkIds:state.removedEducationIds;if(!removed.includes(entry.id))removed.push(entry.id)}if(collection==='languages'&&entry.originalCode&&!state.removedLanguageCodes.includes(entry.originalCode))state.removedLanguageCodes.push(entry.originalCode);state[collection].splice(index,1);state.error='';state.notice='Entry removed from this draft. Save this step to apply the change.';renderWorkspace(state,handlers)});
  document.querySelector('#pe-avatar-file')?.addEventListener('change',event=>{const file=event.target.files?.[0],error=validateProfileUpload(file,'avatar');if(error){state.error=error;renderWorkspace(state,handlers);return}state.avatarFile=file;state.avatarPreview=URL.createObjectURL(file);renderWorkspace(state,handlers)});
  document.querySelector('#pe-company-logo-file')?.addEventListener('change',event=>{const file=event.target.files?.[0],error=validateProfileUpload(file,'avatar');if(error){state.error=error;renderWorkspace(state,handlers);return}state.client.companyLogoFile=file;state.client.companyLogoPreview=URL.createObjectURL(file);renderWorkspace(state,handlers)});
  document.querySelector('#pe-delete-avatar')?.addEventListener('click',()=>handlers.deleteAvatar());
  document.querySelector('#pe-portfolio-file')?.addEventListener('change',event=>{const file=event.target.files?.[0],error=validateProfileUpload(file,'portfolio');if(error){state.error=error;renderWorkspace(state,handlers);return}state.portfolio.file=file;state.portfolio.imagePreview=URL.createObjectURL(file);renderWorkspace(state,handlers)});
  document.querySelector('#pe-delete-portfolio')?.addEventListener('click',()=>handlers.deletePortfolio());
}

async function saveUpload(state,config,kind){
  const file=kind==='avatar'?state.avatarFile:state.portfolio.file;if(!file)return null;
  const bucket=kind==='avatar'?'profile-avatars':'portfolio-assets',path=safeAssetPath(state.user.id,file,kind==='avatar'?'avatar':'portfolio');
  await uploadImage({...config,bucket,path,file,onProgress:value=>{state.uploadProgress=value;renderWorkspace(state,config.handlers)}});
  return path;
}

export async function mountProfileExperience({supabase,user,supabaseUrl,publishableKey,onSignOut,onHome}){
  showRoot(`<div class="pe-public"><header class="pe-header">${featureBrandLink()}<nav aria-label="Account support navigation"><a href="/help" data-route="/help">Help Centre</a><a href="/contact?subject=support" data-route="/contact?subject=support">Contact support</a></nav></header><div class="pe-empty"><span class="pe-kicker">GoWorkora</span><h1>Loading your profile</h1><p>Restoring saved onboarding progress…</p></div></div>`);
  const [profileResult,skillsResult]=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).maybeSingle(),supabase.from('skills').select('id,name,category').eq('is_active',true).order('category').order('name')]);
  if(profileResult.error||!profileResult.data||!['client','freelancer'].includes(profileResult.data.role)){showRoot(`<div class="pe-public"><header class="pe-header">${featureBrandLink()}<nav aria-label="Account support navigation"><a href="/help" data-route="/help">Help Centre</a><a href="/contact?subject=support" data-route="/contact?subject=support">Contact support</a></nav></header><div class="pe-empty"><h1>Profile unavailable</h1><p>Your verified profile could not be loaded.</p></div></div>`);return}
  const p=profileResult.data,state={user,role:p.role,step:Math.max(1,p.onboarding_step),complete:p.onboarding_completed,editing:location.hash.startsWith('#onboarding/'),saving:false,error:'',notice:'',uploadProgress:0,skills:skillsResult.data||[],avatarFile:null,avatarPreview:await signedUrl(supabase,'profile-avatars',p.avatar_path),shared:{displayName:p.display_name||p.full_name||'',firstName:p.first_name||'',lastName:p.last_name||'',countryCode:p.country_code||'',timezone:p.timezone||'UTC',region:p.region||'',locationVisibility:p.location_visibility||'country',profileVisibility:p.profile_visibility||'marketplace',avatarPath:p.avatar_path||null,acceptedTerms:Boolean(p.terms_accepted_at),acceptedPrivacy:Boolean(p.privacy_accepted_at)},client:{jobTitle:'',department:'',hiringRole:'',languageCode:'en',independentClient:false,companyId:null,companyName:'',companyWebsite:'',companyDescription:'',companySize:'',industry:'',companyCountryCode:'',companyLogoPath:null,companyLogoPreview:null,companyLogoFile:null,hiringCategories:[],typicalProjectSize:'',preferredEngagementType:'',billingCountry:'',preferredCurrency:'USD'},freelancer:{professionalTitle:'',bio:'',profileSlug:'',primaryCategory:'',yearsExperience:'',experienceLevel:'intermediate',hourlyRate:'',currency:'USD',weeklyCapacity:'',availabilityStatus:'available',minimumProject:'',skillIds:[]},workHistory:[blankWorkEntry()],educationHistory:[blankEducationEntry()],languages:[blankLanguageEntry()],removedWorkIds:[],removedEducationIds:[],removedLanguageCodes:[],portfolio:{id:null,title:'',description:'',projectUrl:'',imagePath:null,imagePreview:null,isPublished:true,file:null}};
  if(state.role==='client'){
    const {data:c}=await supabase.from('client_profiles').select('*').eq('user_id',user.id).maybeSingle();if(c){Object.assign(state.client,{jobTitle:c.job_title||'',department:c.department||'',hiringRole:c.hiring_role||'',languageCode:c.language_code||'en',independentClient:c.independent_client,companyId:c.company_id,hiringCategories:c.hiring_categories||[],typicalProjectSize:c.typical_project_size||'',preferredEngagementType:c.preferred_engagement_type||'',billingCountry:c.billing_country||p.country_code||'',preferredCurrency:c.preferred_currency||'USD'})}if(c?.company_id){const {data:company}=await supabase.from('companies').select('*').eq('id',c.company_id).maybeSingle();if(company)Object.assign(state.client,{companyName:company.name,companyWebsite:company.website||'',companyDescription:company.description||'',companySize:company.company_size||'',industry:company.industry,companyCountryCode:company.country_code||'',companyLogoPath:company.logo_path||null,companyLogoPreview:company.logo_path?supabase.storage.from('company-logos').getPublicUrl(company.logo_path).data.publicUrl:null})}
  }else{
    const [fr,skillLinks,work,education,languages,portfolio]=await Promise.all([supabase.from('freelancer_profiles').select('*').eq('user_id',user.id).maybeSingle(),supabase.from('freelancer_skills').select('skill_id').eq('freelancer_user_id',user.id),supabase.from('work_experience').select('*').eq('freelancer_user_id',user.id).order('start_date',{ascending:false}),supabase.from('education').select('*').eq('freelancer_user_id',user.id).order('end_year',{ascending:false}),supabase.from('freelancer_languages').select('*').eq('freelancer_user_id',user.id).order('language_name'),supabase.from('portfolio_items').select('*').eq('freelancer_user_id',user.id).order('display_order').limit(1)]);const f=fr.data;if(f)Object.assign(state.freelancer,{professionalTitle:f.professional_title,bio:f.bio,profileSlug:f.profile_slug.startsWith('freelancer-')?normalizeProfileSlug(p.display_name||p.full_name):f.profile_slug,primaryCategory:f.primary_category||'',yearsExperience:f.years_experience==null?'':String(f.years_experience),experienceLevel:f.experience_level,hourlyRate:money(f.hourly_rate_minor),currency:f.currency,weeklyCapacity:f.weekly_capacity_hours==null?'':String(f.weekly_capacity_hours),availabilityStatus:f.availability_status,minimumProject:money(f.minimum_project_minor),skillIds:(skillLinks.data||[]).map(item=>item.skill_id)});state.workHistory=(work.data||[]).map(entry=>({id:entry.id,companyName:entry.company_name,jobTitle:entry.job_title,startDate:entry.start_date,endDate:entry.end_date||'',currentlyWorking:Boolean(entry.currently_working),description:entry.description||''}));if(!state.workHistory.length)state.workHistory=[blankWorkEntry()];state.educationHistory=(education.data||[]).map(entry=>({id:entry.id,institution:entry.institution,qualification:entry.qualification,fieldOfStudy:entry.field_of_study||'',startYear:entry.start_year||'',endYear:entry.end_year||''}));if(!state.educationHistory.length)state.educationHistory=[blankEducationEntry()];state.languages=(languages.data||[]).map(entry=>({originalCode:entry.language_code,code:entry.language_code,name:entry.language_name,proficiency:entry.proficiency_level}));if(!state.languages.length)state.languages=[blankLanguageEntry()];const item=portfolio.data?.[0];if(item)Object.assign(state.portfolio,{id:item.id,title:item.title,description:item.description,projectUrl:item.project_url||'',imagePath:item.image_path,isPublished:item.is_published,imagePreview:await signedUrl(supabase,'portfolio-assets',item.image_path)})
  }
  const handlers={
    home(){unmountProfileExperience();history.replaceState({},'','#top');onHome?.()},
    async signOut(){await onSignOut();unmountProfileExperience()},
    edit(){state.editing=true;state.step=1;location.hash=roleOnboardingDestination(state.role,false);renderWorkspace(state,handlers)},
    back(){state.step=Math.max(1,state.step-1);state.error='';renderWorkspace(state,handlers)},
    async deleteAvatar(){if(!state.shared.avatarPath)return;const previous=state.shared.avatarPath,update=await supabase.from('profiles').update({avatar_path:null}).eq('id',user.id);if(update.error){state.error='The profile image could not be removed.';renderWorkspace(state,handlers);return}await supabase.storage.from('profile-avatars').remove([previous]);state.shared.avatarPath=null;state.avatarPreview=null;state.avatarFile=null;state.notice='Profile image removed.';renderWorkspace(state,handlers)},
    async deletePortfolio(){if(state.portfolio.id){const {error}=await supabase.from('portfolio_items').delete().eq('id',state.portfolio.id);if(error){state.error='The portfolio item could not be deleted.';renderWorkspace(state,handlers);return}if(state.portfolio.imagePath)await supabase.storage.from('portfolio-assets').remove([state.portfolio.imagePath])}Object.assign(state.portfolio,{id:null,title:'',description:'',projectUrl:'',imagePath:null,imagePreview:null,file:null});renderWorkspace(state,handlers)},
    async submit(event){event.preventDefault();if(state.saving)return;state.saving=true;state.error='';state.notice='';renderWorkspace(state,handlers);try{await saveStep(state,{supabase,supabaseUrl,publishableKey,handlers});if(state.step<stepsForRole(state.role).length){state.step+=1;const {error}=await supabase.rpc('set_onboarding_step',{p_step:state.step});if(error)throw error;state.notice='Progress saved. You can return at any time.'}renderWorkspace(state,handlers)}catch(error){state.error=error instanceof Error&&/Enter|Choose|Complete|Accept|Write|Upload|Weekly|profile URL|skills|work-history|education|language|end date|start date|Each/i.test(error.message)?error.message:fail(error);renderWorkspace(state,handlers)}finally{state.saving=false;state.uploadProgress=0;renderWorkspace(state,handlers)}}
  };
  state.editing=location.hash.startsWith('#onboarding/')||!state.complete;renderWorkspace(state,handlers);
}

async function saveStep(state,config){const {supabase}=config,now=new Date().toISOString();
  if(state.role==='client'){
    const error=validateClientStep(state.step,{...state.shared,...state.client});if(error)throw new Error(error);
    if(state.step===1){await saveShared(state,config);const r=await supabase.from('client_profiles').upsert({user_id:state.user.id,job_title:state.client.jobTitle.trim(),department:state.client.department.trim(),hiring_role:state.client.hiringRole.trim(),language_code:state.client.languageCode},{onConflict:'user_id'});if(r.error)throw r.error}
    if(state.step===2){let companyId=state.client.companyId;if(!state.client.independentClient){const payload={owner_user_id:state.user.id,name:state.client.companyName.trim(),slug:`${normalizeProfileSlug(state.client.companyName)||'company'}-${state.user.id.replaceAll('-','').slice(0,8)}`,website:state.client.companyWebsite.trim()||null,description:state.client.companyDescription.trim(),company_size:state.client.companySize,industry:state.client.industry.trim(),country_code:state.client.companyCountryCode};const result=companyId?await supabase.from('companies').update(payload).eq('id',companyId).select('id').single():await supabase.from('companies').insert(payload).select('id').single();if(result.error)throw result.error;companyId=result.data.id;if(state.client.companyLogoFile){const file=state.client.companyLogoFile,extension=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',path=`${companyId}/${crypto.randomUUID()}.${extension}`,previous=state.client.companyLogoPath;await uploadImage({...config,bucket:'company-logos',path,file,onProgress:value=>{state.uploadProgress=value;renderWorkspace(state,config.handlers)}});const logoUpdate=await supabase.from('companies').update({logo_path:path}).eq('id',companyId);if(logoUpdate.error){await supabase.storage.from('company-logos').remove([path]);throw logoUpdate.error}if(previous)await supabase.storage.from('company-logos').remove([previous]);state.client.companyLogoPath=path;state.client.companyLogoPreview=supabase.storage.from('company-logos').getPublicUrl(path).data.publicUrl;state.client.companyLogoFile=null}}const r=await supabase.from('client_profiles').upsert({user_id:state.user.id,company_id:state.client.independentClient?null:companyId,independent_client:state.client.independentClient},{onConflict:'user_id'});if(r.error)throw r.error;state.client.companyId=companyId}
    if(state.step===3){const r=await supabase.from('client_profiles').update({hiring_categories:state.client.hiringCategories,typical_project_size:state.client.typicalProjectSize,preferred_engagement_type:state.client.preferredEngagementType}).eq('user_id',state.user.id);if(r.error)throw r.error}
    if(state.step===4){const r=await supabase.from('client_profiles').update({billing_country:state.client.billingCountry,preferred_currency:state.client.preferredCurrency}).eq('user_id',state.user.id);if(r.error)throw r.error}
  }else{
    const error=validateFreelancerStep(state.step,{...state.shared,...state.freelancer,availableCategories:[...new Set(state.skills.map(skill=>skill.category))]});if(error)throw new Error(error);
    if(state.step===1){await saveShared(state,config);const r=await supabase.from('freelancer_profiles').upsert({user_id:state.user.id,professional_title:state.freelancer.professionalTitle.trim(),bio:state.freelancer.bio.trim(),country_code:state.shared.countryCode,timezone:state.shared.timezone,profile_slug:normalizeProfileSlug(state.freelancer.profileSlug)},{onConflict:'user_id'});if(r.error)throw r.error}
    if(state.step===2){const profileUpdate=await supabase.from('freelancer_profiles').update({primary_category:state.freelancer.primaryCategory,years_experience:Number(state.freelancer.yearsExperience)}).eq('user_id',state.user.id);if(profileUpdate.error)throw profileUpdate.error;const existing=await supabase.from('freelancer_skills').select('skill_id').eq('freelancer_user_id',state.user.id);if(existing.error)throw existing.error;const removed=(existing.data||[]).map(item=>item.skill_id).filter(id=>!state.freelancer.skillIds.includes(id));if(removed.length){const r=await supabase.from('freelancer_skills').delete().eq('freelancer_user_id',state.user.id).in('skill_id',removed);if(r.error)throw r.error}const r=await supabase.from('freelancer_skills').upsert(state.freelancer.skillIds.map(skill_id=>({freelancer_user_id:state.user.id,skill_id,proficiency_level:'advanced',years_experience:Number(state.freelancer.yearsExperience)})),{onConflict:'freelancer_user_id,skill_id'});if(r.error)throw r.error}
    if(state.step===3){const r=await supabase.from('freelancer_profiles').update({hourly_rate_minor:minor(state.freelancer.hourlyRate),currency:state.freelancer.currency,experience_level:state.freelancer.experienceLevel,availability_status:state.freelancer.availabilityStatus,weekly_capacity_hours:Number(state.freelancer.weeklyCapacity),minimum_project_minor:state.freelancer.minimumProject?minor(state.freelancer.minimumProject):null}).eq('user_id',state.user.id);if(r.error)throw r.error}
    if(state.step===4)await saveOptionalHistory(state,supabase);
    if(state.step===5)await saveFeaturedPortfolio(state,config);
  }
  if(state.step===stepsForRole(state.role).length){const agreement=await supabase.from('profiles').update({terms_accepted_at:now,privacy_accepted_at:now}).eq('id',state.user.id);if(agreement.error)throw agreement.error;const completed=await supabase.rpc('finalize_profile_onboarding');if(completed.error)throw completed.error;state.complete=true;state.editing=false;state.notice='Your profile is complete and ready to use.';location.hash=roleOnboardingDestination(state.role,true)}
}

async function saveShared(state,config){const {supabase}=config;const r=await supabase.from('profiles').update({display_name:state.shared.displayName.trim(),full_name:state.shared.displayName.trim(),first_name:state.shared.firstName.trim(),last_name:state.shared.lastName.trim(),country_code:state.shared.countryCode||null,timezone:state.shared.timezone,region:state.shared.region.trim()||null,location_visibility:state.shared.locationVisibility,profile_visibility:state.shared.profileVisibility}).eq('id',state.user.id);if(r.error)throw r.error;if(state.avatarFile){const path=await saveUpload(state,config,'avatar'),previous=state.shared.avatarPath;const update=await supabase.from('profiles').update({avatar_path:path}).eq('id',state.user.id);if(update.error)throw update.error;if(previous)await supabase.storage.from('profile-avatars').remove([previous]);state.shared.avatarPath=path;state.avatarFile=null}}
async function saveOptionalHistory(state,supabase){
  for(const entry of state.workHistory){const error=validateWorkHistoryEntry(entry);if(error)throw new Error(error)}
  for(const entry of state.educationHistory){const error=validateEducationEntry(entry);if(error)throw new Error(error)}
  for(const entry of state.languages){const error=validateLanguageEntry(entry);if(error)throw new Error(error)}
  const languageCodes=state.languages.filter(hasLanguageValue).map(entry=>String(entry.code||'').trim().toLowerCase());
  if(new Set(languageCodes).size!==languageCodes.length)throw new Error('Each language code can be added only once.');
  for(const entry of state.workHistory.filter(hasWorkValue)){
    const payload={freelancer_user_id:state.user.id,company_name:entry.companyName.trim(),job_title:entry.jobTitle.trim(),start_date:entry.startDate,end_date:entry.currentlyWorking?null:entry.endDate,currently_working:Boolean(entry.currentlyWorking),description:entry.description.trim()};
    if(entry.id){const result=await supabase.from('work_experience').update(payload).eq('id',entry.id).eq('freelancer_user_id',state.user.id);if(result.error)throw result.error}
    else{const result=await supabase.from('work_experience').insert(payload).select('id').single();if(result.error)throw result.error;entry.id=result.data.id}
  }
  for(const entry of state.educationHistory.filter(hasEducationValue)){
    const payload={freelancer_user_id:state.user.id,institution:entry.institution.trim(),qualification:entry.qualification.trim(),field_of_study:entry.fieldOfStudy.trim(),start_year:entry.startYear===''?null:Number(entry.startYear),end_year:entry.endYear===''?null:Number(entry.endYear)};
    if(entry.id){const result=await supabase.from('education').update(payload).eq('id',entry.id).eq('freelancer_user_id',state.user.id);if(result.error)throw result.error}
    else{const result=await supabase.from('education').insert(payload).select('id').single();if(result.error)throw result.error;entry.id=result.data.id}
  }
  if(state.removedWorkIds.length){const result=await supabase.from('work_experience').delete().eq('freelancer_user_id',state.user.id).in('id',state.removedWorkIds);if(result.error)throw result.error;state.removedWorkIds=[]}
  if(state.removedEducationIds.length){const result=await supabase.from('education').delete().eq('freelancer_user_id',state.user.id).in('id',state.removedEducationIds);if(result.error)throw result.error;state.removedEducationIds=[]}
  if(state.removedLanguageCodes.length){const result=await supabase.from('freelancer_languages').delete().eq('freelancer_user_id',state.user.id).in('language_code',state.removedLanguageCodes);if(result.error)throw result.error;state.removedLanguageCodes=[]}
  for(const entry of state.languages.filter(hasLanguageValue)){
    const normalizedCode=String(entry.code).trim().toLowerCase();
    if(entry.originalCode&&entry.originalCode!==normalizedCode){const removed=await supabase.from('freelancer_languages').delete().eq('freelancer_user_id',state.user.id).eq('language_code',entry.originalCode);if(removed.error)throw removed.error}
    const result=await supabase.from('freelancer_languages').upsert({freelancer_user_id:state.user.id,language_code:normalizedCode,language_name:entry.name.trim(),proficiency_level:entry.proficiency},{onConflict:'freelancer_user_id,language_code'});if(result.error)throw result.error;entry.code=normalizedCode;entry.originalCode=normalizedCode
  }
}
async function saveFeaturedPortfolio(state,config){const {supabase}=config;if(!state.portfolio.title&&!state.portfolio.file)return;if(!state.portfolio.title)throw new Error('Add a title to your portfolio item.');const payload={freelancer_user_id:state.user.id,title:state.portfolio.title,description:state.portfolio.description,project_url:state.portfolio.projectUrl||null,is_published:state.portfolio.isPublished,display_order:0};const r=state.portfolio.id?await supabase.from('portfolio_items').update(payload).eq('id',state.portfolio.id).select('id').single():await supabase.from('portfolio_items').insert(payload).select('id').single();if(r.error)throw r.error;state.portfolio.id=r.data.id;if(state.portfolio.file){const path=await saveUpload(state,config,'portfolio'),previous=state.portfolio.imagePath;const update=await supabase.from('portfolio_items').update({image_path:path}).eq('id',r.data.id);if(update.error)throw update.error;if(previous)await supabase.storage.from('portfolio-assets').remove([previous]);state.portfolio.imagePath=path;state.portfolio.file=null}}

export async function mountPublicFreelancerProfile({supabase,slug,onHome,user,role}){
  showRoot(`<div class="pe-public"><header class="pe-header">${featureBrandLink()}<nav aria-label="Public profile navigation"><a href="/find-talent" data-route="/find-talent">Find talent</a><a href="/find-work" data-route="/find-work">Find work</a><a href="/how-it-works" data-route="/how-it-works">How it works</a></nav></header><div class="pe-empty"><h1>Loading public profile</h1><p>Fetching approved public information only…</p></div></div>`);
  const {data,error}=await supabase.from('freelancer_public_profiles').select('*').eq('profile_slug',normalizeProfileSlug(slug)).maybeSingle();
  if(error||!data?.user_id){
    showRoot(`<div class="pe-public"><header class="pe-header">${featureBrandLink()}<nav aria-label="Public profile navigation"><a href="/find-talent" data-route="/find-talent">Find talent</a><a href="/find-work" data-route="/find-work">Find work</a><a href="/help" data-route="/help">Help Centre</a></nav></header><div class="pe-empty"><h1>Profile not found</h1><p>This profile is private, incomplete, or unavailable.</p><button class="pe-button dark" id="pe-public-home">Explore GoWorkora</button></div></div>`);
    document.querySelector('#pe-public-home').onclick=()=>{unmountProfileExperience();history.replaceState({},'','#top');onHome?.()};
    return;
  }
  const [links,items,workHistory,education,languages,avatar]=await Promise.all([
    supabase.from('freelancer_skills').select('skill_id').eq('freelancer_user_id',data.user_id),
    supabase.from('portfolio_items').select('*').eq('freelancer_user_id',data.user_id).eq('is_published',true).order('display_order'),
    supabase.from('work_experience').select('company_name,job_title,start_date,end_date,currently_working,description').eq('freelancer_user_id',data.user_id).order('start_date',{ascending:false}),
    supabase.from('education').select('institution,qualification,field_of_study,start_year,end_year').eq('freelancer_user_id',data.user_id).order('end_year',{ascending:false}),
    supabase.from('freelancer_languages').select('language_name,proficiency_level').eq('freelancer_user_id',data.user_id).order('language_name'),
    signedUrl(supabase,'profile-avatars',data.avatar_path),
  ]);
  const ids=(links.data||[]).map(item=>item.skill_id);
  const skills=ids.length?(await supabase.from('skills').select('name').in('id',ids)).data||[]:[];
  const portfolio=await Promise.all((items.data||[]).map(async item=>({...item,url:await signedUrl(supabase,'portfolio-assets',item.image_path)})));
  const hireAction=role==='client'?'<button class="pe-button lime" id="pe-contact-talent">Message professional</button>':!user?`<a class="pe-button lime" href="/signup/client?returnTo=${encodeURIComponent(`/find-talent/${data.profile_slug}`)}" data-route="/signup/client">Sign up to hire</a>`:'';
  const professionalMeta=[
    data.primary_category,
    data.years_experience==null?'':`${Number(data.years_experience)} years experience`,
    data.public_location?`◎ ${data.public_location}`:'',
    timezoneOverlapSummary(data.timezone),
  ].filter(Boolean);
  showRoot(`<div class="pe-public"><header class="pe-header">${featureBrandButton('pe-public-home')}<nav aria-label="Public profile navigation"><a href="/find-talent" data-route="/find-talent">Find talent</a><a href="/find-work" data-route="/find-work">Find work</a><a href="/how-it-works" data-route="/how-it-works">How it works</a></nav><button class="pe-button" id="pe-explore-marketplace">Explore marketplace</button></header><article class="pe-public-card"><div class="pe-public-hero"><div class="pe-public-avatar">${avatar?`<img src="${esc(avatar)}" alt="${esc(safePublicDisplayName(data.display_name))} profile">`:'W'}</div><div>${data.is_demo?'<span class="demo-badge">Demo</span>':''}${data.is_verified?'<span class="pe-role">✓ Identity verified</span>':''}<h1>${esc(safePublicDisplayName(data.display_name))}</h1><p>${esc(safePublicProfessionalTitle(data.professional_title))}</p>${data.is_demo?'<p class="demo-disclaimer">Fictional demonstration profile — not a real freelancer or customer.</p>':''}<div class="pe-public-meta">${professionalMeta.map(item=>`<span>${esc(item)}</span>`).join('')}</div></div><div class="pe-public-rate-action"><strong class="pe-rate">${esc(data.currency)} ${esc(money(data.hourly_rate_minor))}/hr</strong>${hireAction}</div></div><div class="pe-public-body"><section><h2>About</h2><p>${esc(data.bio)}</p></section><section><h2>Skills</h2><div class="pe-tags">${skills.map(skill=>`<span>${esc(skill.name)}</span>`).join('')}</div></section>${workHistory.data?.length?`<section><h2>Work history</h2><div class="pe-public-history">${workHistory.data.map(item=>`<article><div><strong>${esc(item.job_title)}</strong><span>${esc(item.company_name)}</span></div><small>${esc(item.start_date)} — ${esc(item.currently_working?'Present':item.end_date||'Not specified')}</small>${item.description?`<p>${esc(item.description)}</p>`:''}</article>`).join('')}</div></section>`:''}${education.data?.length?`<section><h2>Education</h2><div class="pe-public-history">${education.data.map(item=>`<article><div><strong>${esc(item.qualification)}</strong><span>${esc(item.institution)}</span></div><small>${esc([item.field_of_study,item.start_year&&item.end_year?`${item.start_year}–${item.end_year}`:item.end_year||item.start_year].filter(Boolean).join(' · '))}</small></article>`).join('')}</div></section>`:''}${languages.data?.length?`<section><h2>Languages</h2><div class="pe-tags">${languages.data.map(item=>`<span>${esc(item.language_name)} · ${esc(item.proficiency_level)}</span>`).join('')}</div></section>`:''}${portfolio.length?`<section><h2>Portfolio</h2><div class="pe-portfolio">${portfolio.map(item=>`<article>${item.url?`<div class="pe-image"><img src="${esc(item.url)}" alt="${esc(item.title)} project"></div>`:''}<h3>${esc(item.title)}</h3><p>${esc(item.description)}</p></article>`).join('')}</div></section>`:''}</div></article></div>`);
  document.querySelectorAll('#pe-public-home,#pe-explore-marketplace').forEach(button=>button.onclick=()=>{unmountProfileExperience();history.replaceState({},'','#top');onHome?.()});
  document.querySelector('#pe-contact-talent')?.addEventListener('click',()=>openTalentContactDialog({supabase,freelancerUserId:data.user_id,displayName:safePublicDisplayName(data.display_name),professionalTitle:safePublicProfessionalTitle(data.professional_title)}));
}
